[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  package = "@netlify/plugin-nextjs"

[template.environment]
  SITE_NAME = "NextJS + NetlifyCMS + TailwindCSS"