backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", default: "/images/default.jpg"}
  - name: "settings"
    label: "Settings"
    files: 
      - label: "General"
        name: "general"
        file: "content/settings/general.md"
        fields:
          - {label: "Site Name", name: "site-name", widget: "string"}
          - {label: "Description", name:"description", widget: "text"}

