backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", default: "/images/default.jpg"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: content/pages/home.md
        fields:
          - { name: "title", label: "title", widget: "string", default: "Home" }
          - { name: "heading", label: "Heading" }
          - { name: "subheading", label: "Subheading", widget: "text"  }
          - { label: "Image", name: "image", widget: "image", default: "/images/default.jpg" }

      - label: "About"
        name: "about"
        file: content/pages/about.md
        fields:
          - { name: "title", label: "title", widget: "string", default: "About" }
          - { name: "heading", label: "Heading" }
          - { name: "subheading", label: "Subheading", widget: "text"  }
      - label: "Contact"
        name: "contact"
        file: content/pages/contact.md
        fields:
          - { name: "title", label: "title", widget: "string", default: "Contact" }
          - { name: "heading", label: "Heading" }
          - { name: "subheading", label: "Subheading", widget: "text"  }

  - name: "settings"
    label: "Settings"
    delete: false
    files: 
      - label: "General"
        name: "general"
        file: "config.json"
        description: "General site settings"
        fields:
          - {label: "URL", name: "base_url", widget: "string", hint: "Do not enter trailing slash of the URL"}
          - {label: "Site Name", name: "site_name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}

